[package]
name = "actix_web"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
actix-files = "0.6.0"

# tokio = "1.19.2"
# tokio-postgres = "0.7.6" # TODO Only if feature is enabled
# async-trait = "0.1.56"

log = "0.4"
pretty_env_logger = "0.4"
