name: Continuous Integration

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  build_all_examples:
    name: Build all the examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v11
        with:
          name: nixweblib
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build examples
        run: nix run ./examples#build_all
